// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://tsfvdoteqtqgyecbzzxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZnZkb3RlcXRxZ3llY2J6enhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NzA3NzksImV4cCI6MjA4MzU0Njc3OX0.pIF75f8_U6fzvwOPKnwwhXpgMWxikDvE9lLuQepCH4U";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
